print("danish")
print(2+3)
print("i am learning in codanics")
print("this is my car")
print("to day")
print(6+5-7)
print("my day")
print("hellow")
print(7+3-8*2)
print("my number")
print("he book")
print(99+1)
print(8+7)
print(9+3)+(4*2)-6   